name: Bitbucket YAML Patcher
description: Greet someone and record the time
inputs:
  file:
    description: YAML file to patch. For example 'ken-test/applications/default/security/ussd/values.yaml'
    required: true
  value:
    description: For example `v1.2.3`
    required: true
    default: ${{ startsWith(github.ref,'refs/tags') && github.ref_name || github.sha }}
  username:
    description: Username for login to Git URL
    required: true
    default: carepaybot
  password:
    required: true
  jsonpath:
    required: true
    default: $.microservice.image
  workspace:
    description: Bitbucket workspace slug
    required: true
    default: carepaydev
  repository:
    description: Bitbucket repository slug
    required: true
    default: central-configs
runs:
  using: "node24"
  main: "dist/index.js"
